FROM mcr.microsoft.com/dotnet/core/sdk:3.1-bionic

WORKDIR /src/Instagram.Services.Newsfeed
COPY . /src/Instagram.Services.Newsfeed

RUN apt-get update \
 && apt-get install -y --no-install-recommends unzip \
 && curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l /vsdbg

ARG BUILD_CONFIGURATION=Debug
EXPOSE 4004