FROM mcr.microsoft.com/dotnet/core/sdk:3.1-bionic

WORKDIR /src/Instagram.Services.Post
COPY . /src/Instagram.Services.Post

RUN apt-get update \
 && apt-get install -y --no-install-recommends unzip \
 && curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l /vsdbg

RUN apt install libgdiplus -y
RUN apt install ffmpeg -y

ARG BUILD_CONFIGURATION=Debug
EXPOSE 4002